from .boa_constrictor import Boa_Constrictor
from .corn_snake import Corn_Snake
from .kingsnake import Kingsnake
from .python import Python
from .rat_snake import Rat_Snake
from .catfish import Catfish
from .duck import Duck
from .frog import Frog
from .goldfish import Goldfish
from .turtle import Turtle
from .donkey import Donkey
from .goat import Goat
from .llama import Llama
from .pig import Pig
from .sheep import Sheep
